/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.drink.ordering.system.infrastructure.kafka.order.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BaristaAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4210040436341822422L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BaristaAvroModel\",\"namespace\":\"com.drink.ordering.system.infrastructure.kafka.order.avro.model\",\"fields\":[{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"orderPreparationStatus\",\"type\":{\"type\":\"enum\",\"name\":\"OrderPreparationStatus\",\"symbols\":[\"ORDER_ACCEPTED\",\"ORDER_CANCELED\",\"ORDER_FINISHED\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BaristaAvroModel> ENCODER =
      new BinaryMessageEncoder<BaristaAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BaristaAvroModel> DECODER =
      new BinaryMessageDecoder<BaristaAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BaristaAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BaristaAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BaristaAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BaristaAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BaristaAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BaristaAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BaristaAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BaristaAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String orderId;
  private com.drink.ordering.system.infrastructure.kafka.order.avro.model.OrderPreparationStatus orderPreparationStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BaristaAvroModel() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param orderPreparationStatus The new value for orderPreparationStatus
   */
  public BaristaAvroModel(java.lang.String orderId, com.drink.ordering.system.infrastructure.kafka.order.avro.model.OrderPreparationStatus orderPreparationStatus) {
    this.orderId = orderId;
    this.orderPreparationStatus = orderPreparationStatus;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return orderPreparationStatus;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = value$ != null ? value$.toString() : null; break;
    case 1: orderPreparationStatus = (com.drink.ordering.system.infrastructure.kafka.order.avro.model.OrderPreparationStatus)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.String getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.String value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'orderPreparationStatus' field.
   * @return The value of the 'orderPreparationStatus' field.
   */
  public com.drink.ordering.system.infrastructure.kafka.order.avro.model.OrderPreparationStatus getOrderPreparationStatus() {
    return orderPreparationStatus;
  }


  /**
   * Sets the value of the 'orderPreparationStatus' field.
   * @param value the value to set.
   */
  public void setOrderPreparationStatus(com.drink.ordering.system.infrastructure.kafka.order.avro.model.OrderPreparationStatus value) {
    this.orderPreparationStatus = value;
  }

  /**
   * Creates a new BaristaAvroModel RecordBuilder.
   * @return A new BaristaAvroModel RecordBuilder
   */
  public static com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel.Builder newBuilder() {
    return new com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel.Builder();
  }

  /**
   * Creates a new BaristaAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BaristaAvroModel RecordBuilder
   */
  public static com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel.Builder newBuilder(com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel.Builder other) {
    if (other == null) {
      return new com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel.Builder();
    } else {
      return new com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new BaristaAvroModel RecordBuilder by copying an existing BaristaAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new BaristaAvroModel RecordBuilder
   */
  public static com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel.Builder newBuilder(com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel other) {
    if (other == null) {
      return new com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel.Builder();
    } else {
      return new com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for BaristaAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BaristaAvroModel>
    implements org.apache.avro.data.RecordBuilder<BaristaAvroModel> {

    private java.lang.String orderId;
    private com.drink.ordering.system.infrastructure.kafka.order.avro.model.OrderPreparationStatus orderPreparationStatus;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.orderPreparationStatus)) {
        this.orderPreparationStatus = data().deepCopy(fields()[1].schema(), other.orderPreparationStatus);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing BaristaAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderPreparationStatus)) {
        this.orderPreparationStatus = data().deepCopy(fields()[1].schema(), other.orderPreparationStatus);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.String getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel.Builder setOrderId(java.lang.String value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderPreparationStatus' field.
      * @return The value.
      */
    public com.drink.ordering.system.infrastructure.kafka.order.avro.model.OrderPreparationStatus getOrderPreparationStatus() {
      return orderPreparationStatus;
    }


    /**
      * Sets the value of the 'orderPreparationStatus' field.
      * @param value The value of 'orderPreparationStatus'.
      * @return This builder.
      */
    public com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel.Builder setOrderPreparationStatus(com.drink.ordering.system.infrastructure.kafka.order.avro.model.OrderPreparationStatus value) {
      validate(fields()[1], value);
      this.orderPreparationStatus = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'orderPreparationStatus' field has been set.
      * @return True if the 'orderPreparationStatus' field has been set, false otherwise.
      */
    public boolean hasOrderPreparationStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'orderPreparationStatus' field.
      * @return This builder.
      */
    public com.drink.ordering.system.infrastructure.kafka.order.avro.model.BaristaAvroModel.Builder clearOrderPreparationStatus() {
      orderPreparationStatus = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BaristaAvroModel build() {
      try {
        BaristaAvroModel record = new BaristaAvroModel();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.String) defaultValue(fields()[0]);
        record.orderPreparationStatus = fieldSetFlags()[1] ? this.orderPreparationStatus : (com.drink.ordering.system.infrastructure.kafka.order.avro.model.OrderPreparationStatus) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BaristaAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<BaristaAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BaristaAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<BaristaAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










