/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.drink.ordering.system.infrastructure.kafka.order.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum OrderPreparationStatus implements org.apache.avro.generic.GenericEnumSymbol<OrderPreparationStatus> {
  ORDER_ACCEPTED, ORDER_CANCELED, ORDER_FINISHED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderPreparationStatus\",\"namespace\":\"com.drink.ordering.system.infrastructure.kafka.order.avro.model\",\"symbols\":[\"ORDER_ACCEPTED\",\"ORDER_CANCELED\",\"ORDER_FINISHED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
