version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - ${GLOBAL_NETWORK}
    restart: unless-stopped

volumes:
  postgres: